name: Release

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows] # 需要打包的系统
        goarch: [amd64, arm64] # 需要打包的架构
        exclude: # 排除某些平台和架构
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.37
        with:
          github_token: ${{ secrets.REPO_TOKEN }} # 用于往 Release 中添加文件
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.19 # 指定编译使用的 Golang 版本
          binary_name: "cube" # 可以指定二进制文件的名称
          pre_command: "export CGO_ENABLED=1"
          ldflags: "-s -w"
          executable_compression: upx
          extra_files: README.md # 需要包含的额外文件
          overwrite: true
