name: Release

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.37
        with:
          github_token: ${{ secrets.REPO_TOKEN }} # 用于往 Release 中添加文件
          goos: linux
          goarch: amd64
          goversion: 1.19 # 指定编译使用的 Golang 版本
          binary_name: "cube" # 可以指定二进制文件的名称
          ldflags: "-extldflags -static -s -w"
          executable_compression: upx
          extra_files: README.md # 需要包含的额外文件
          overwrite: true
      - uses: wangyoucao577/go-release-action@v1.37
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          goos: windows
          goarch: amd64
          goversion: 1.19
          binary_name: "cube"
          pre_command: "apt-get update && apt-get install --no-install-recommends -y gcc-mingw-w64-x86-64 && export CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++"
          ldflags: "-extldflags -static -s -w"
          executable_compression: upx
          extra_files: README.md
          overwrite: true
