name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Package
      run: |
        tar cvf cube-linux-amd64-latest.tar.gz cube

    - name: Upload to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: cube-linux-amd64-latest.tar.gz
        tag: ${{ github.ref }}
        release_name: ${{ github.ref }}
        overwrite: true
        file_glob: true
        body: ""
