name: Release

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: |
          go build -ldflags "-extldflags -static -s -w" -o .cube .
          apt-get install -y upx
          upx -9 -q -o cube .cube
          tar -zcvf cube-main-linux-amd64.tar.gz cube
      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cube-main-linux-amd64.tar.gz
          tag: ${{ github.ref }}
          release_name: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: ""
