/**
 * Byte array generated by native go methods.
 */
interface NativeByteArray extends Array<number> {
    /** It is not allowed to create it by yourself, it can only be generated by native go methods. */
    "Native Go Slice";
}

/**
 * Service context.
 */
interface ServiceContext {
    getHeader(): { [name: string]: string; };
    getURL(): { path: string; params: { [name: string]: string[]; }; };
    getBody(): NativeByteArray;
    getJsonBody(): any;
    getMethod(): "GET" | "POST" | "PUT" | "DELETE";
    getForm(): { [name: string]: string[]; };
    getPathVariables(): { [name: string]: string; };
    getFile(name: string): { name: string; size: number; data: NativeByteArray; };
    getCerts(): { raw: NativeByteArray; }[];
    upgradeToWebSocket(): ServiceWebSocket;
    getReader(): { readByte(): number; read(count: number): NativeByteArray; };
    getPusher(): { push(target: string, options: any): void; };
    write(data: Uint8Array | NativeByteArray | string): number;
    flush(): void;
    resetTimeout(timeout: number): void;
}

/**
 * Service websocket.
 */
interface ServiceWebSocket {
    read(): { messageType: number; data: NativeByteArray; };
    send(data: Uint8Array | NativeByteArray | string);
    close();
}

declare class ServiceResponse {
    constructor(status: number, header: { [name: string]: string | number; }, data?: Uint8Array | NativeByteArray | string);
    setStatus(status: number): void;
    setHeader(header: { [name: string]: string; }): void;
    setData(data: Uint8Array | NativeByteArray | string): void;
}

/**
 * Buffer.
 */
declare interface Buffer extends NativeByteArray {
    toString(encoding?: "utf8" | "hex" | "base64" | "base64url"): string;
}
declare interface BufferConstructor {
    from(input: string | Uint8Array | NativeByteArray, encoding?: "utf8" | "hex" | "base64" | "base64url"): Buffer;
}
var Buffer: BufferConstructor;

type BlockingQueue = {
    put(input: any, timeout: number): void;
    poll(timeout: number): any;
    drain(size: number, timeout: number): any[];
};
declare function $native(name: "bqueue"): (size: number) => BlockingQueue;

declare function $native(name: "cache"): {
    set(key: any, value: any, timeout: number): void;
    get(key: any): any;
};

declare function $native(name: "crypto"): {
    createHash(algorithm: "md5" | "sha1" | "sha256" | "sha512"): {
        sum(input: string | Uint8Array | NativeByteArray): NativeByteArray;
    };
    createHmac(algorithm: "md5" | "sha1" | "sha256" | "sha512"): {
        sum(input: string | Uint8Array | NativeByteArray, key: string | Uint8Array | NativeByteArray): NativeByteArray;
    };
    createRsa(): {
        generateKey(): { privateKey: NativeByteArray; publicKey: NativeByteArray; };
        encrypt(input: string | Uint8Array | NativeByteArray, key: string | Uint8Array | NativeByteArray): NativeByteArray;
        decrypt(input: string | Uint8Array | NativeByteArray, key: string | Uint8Array | NativeByteArray): NativeByteArray;
        sign(input: string | Uint8Array | NativeByteArray, key: string | Uint8Array | NativeByteArray, algorithm: "md5" | "sha1" | "sha256" | "sha512"): NativeByteArray;
        signPss(input: string | Uint8Array | NativeByteArray, key: string | Uint8Array | NativeByteArray, algorithm: "md5" | "sha1" | "sha256" | "sha512"): NativeByteArray;
        verify(input: string | Uint8Array | NativeByteArray, sign: string | Uint8Array | NativeByteArray, key: string | Uint8Array | NativeByteArray, algorithm: "md5" | "sha1" | "sha256" | "sha512"): boolean;
        verifyPss(input: string | Uint8Array | NativeByteArray, sign: string | Uint8Array | NativeByteArray, key: string | Uint8Array | NativeByteArray, algorithm: "md5" | "sha1" | "sha256" | "sha512"): boolean;
    };
};

declare function $native(name: "db"): {
    beginTx(): {
        query(stmt: string, ...params: any[]): any[];
        exec(stmt: string, ...params: any[]): number;
        commit(): void;
        rollback(): void;
    };
    query(stmt: string, ...params: any[]): any[];
    exec(stmt: string, ...params: any[]): number;
};

type Decimal = {
    add(value: Decimal): Decimal;
    sub(value: Decimal): Decimal;
    mul(value: Decimal): Decimal;
    div(value: Decimal): Decimal;
};
declare function $native(name: "decimal"): (value: string) => Decimal;

declare function $native(name: "email"): (host: string, port: number, username: string, password: string) => {
    send(receivers: string[], subject: string, content: string, attachments: { Name: string; ContentType: string; Base64: string; }[]): void;
};

declare function $native(name: "event"): {
    emit(topic: string, data: any): void;
    on(topic: string, func: (data: any) => void): void;
};

declare function $native(name: "file"): {
    read(name: string): NativeByteArray;
    readRange(name: string, offset: number, length: number): NativeByteArray;
    write(name: string, content: string | Uint8Array | NativeByteArray): void;
    writeRange(name: string, offset: number, content: string | Uint8Array | NativeByteArray): void;
    stat(name: string): {
        name(): string;
        size(): number;
        isDir(): boolean;
        mode(): string;
        modTime(): string;
    };
    list(name: string): string[];
};

declare function $native(name: "http"): (options?: { caCert?: string; cert?: string; key?: string; insecureSkipVerify?: boolean; isHttp3?: boolean; proxy?: string; }) => {
    request(method: string, url: string, header?: { [name: string]: string; }, body?: string | Uint8Array | NativeByteArray): { status: number; header: { [name: string]: string; }; data: { toBytes(): NativeByteArray; toString(): string; toJson(): any; }; };
};

type Image = {
    width: number;
    height: number;
    get(x: number, y: number): number;
    set(x: number, y: number, p: number): void;
    toBytes(): NativeByteArray;
    resize(width: number, height: number): Image;
};
declare function $native(name: "image"): {
    new(width: number, height: number): Image;
    parse(input: Uint8Array | NativeByteArray): Image;
};

declare function $native(name: "lock"): (name: string) => {
    lock(timeout: number): void;
    unlock(): void;
};

declare function $native(name: "pipe"): (name: string) => BlockingQueue;

type TCPSocketConnection = {
    read(size?: number): NativeByteArray;
    readLine(): NativeByteArray;
    write(data: string | Uint8Array | NativeByteArray): number;
    close(): void;
};
type UDPSocketConnection = {
    read(size?: number): NativeByteArray;
    write(data: string | Uint8Array | NativeByteArray, host?: string, port?: number): number;
    close(): void;
};
declare function $native(name: "socket"): {
    (protocol: "tcp"): {
        dial(host: string, port: number): TCPSocketConnection;
        listen(port: number): {
            accept(): TCPSocketConnection;
        };
    }
    (protocol: "udp"): {
        dial(host: string, port: number): UDPSocketConnection;
        listen(port: number): UDPSocketConnection;
        listenMulticast(host: string, port: number): UDPSocketConnection;
    }
};

declare function $native(name: "template"): (name: string, input: { [name: string]: any; }) => string;

declare function $native(name: "ulid"): () => string;

type XmlNode = {
    find(expr: string): XmlNode[];
    findOne(expr: string): XmlNode;
    innerText(): string;
    toString(): string;
};
declare function $native(name: "xml"): (content: string) => XmlNode;

declare function $native(name: "zip"): {
    write(data: { [name: string]: string | NativeByteArray; }): NativeByteArray;
    read(data: Uint8Array | NativeByteArray): {
        getFiles(): {
            getName(): string;
            getData(): NativeByteArray;
        }[];
    };
};
